1. Сравните метрики hit_rate@k, precision@k.   
Какую метрику использовать предпочтительно и почему?  
Приведите пример 2-3 задач (опишите, что является клиентом, что товаром), в которой более уместно использовать метрику hit_rate?


hit_rate@k характеризует удачна ли рекомендация, precision@k - на сколько удачна. hit_rate@k уместно использовать при рекомендации дорогих товаров(покупается всё равно только один), услуг, подбора канала коммуникпции

2. В метрике NDCG@k мы используем логарифм в знаменателе. Как Вы думаете, почему именно логарифм? Какую функцию можно использовать вместо логарифма? Привидите пример метрик/подходов к предобработке данных/функций ошибок в ML, где также в  логарифм.

>Использование логарифма как функции дисконтирования можно объяснить следующими интуитивными соображениями: с точки зрения ранжирования позиции в начале списка отличаются гораздо сильнее, чем позиции в его конце. Так, в случае поискового движка между позициями 1 и 11 целая пропасть (лишь в нескольких случаях из ста пользователь заходит дальшей первой страницы поисковой выдачи), а между позициями 101 и 111 особой разницы нет — до них мало кто доходит. Эти субъективные соображения прекрасно выражаются с помощью логарифма:

Монотонно возрастающей(например степеннная 1/2))


3. Какие еще метрики (Вы можете вспомнить уже пройденные Вами или посмотреть в интернете) могут использоваться для рекомендательных систем (приведите примеры метрики **и чем являются интеракции**, чтобы она могла быть использована).

Метрики на основе ранговой корреляции

4. boughted = [1, 3, 5, 7, 9, 11]  
recommended = [2, 5, 7, 4, 11, 9, 8, 10, 12, 3]  
Посчитайте на этих данных pr@8, rec@8, AP@8, NDCG@8, MRR@8,  
Сначала поссчитайет "руками", а затем подтвердите рассчеты с помощью функций (некоторые были на семинаре, некоторые нужно будут написать самостоятельно)

IDCG должен считаться для всех 8 позиций рекомендаций

**Пример выполнения 4го задания**

MSE на  
$y = [0, 2]$  
$y_{pred} = [1, 2]$

MSE = $0.5*((0 - 1)^2 + (2-2)^2) = 0.5$ 

In [3]:
import numpy as np
((np.array([0, 2]) - np.array([1, 2]))**2).mean()

0.5

In [4]:
boughted = [1, 3, 5, 7, 9, 11]
recommended = [2, 5, 7, 4, 11, 9, 8, 10, 12, 3]

In [16]:
np.isin(recommended, boughted).astype(int)

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1])

In [17]:
pr_at_8=(0+1+1+0+1+1+0+0)/(8)
pr_at_8

0.5

In [47]:
def precision_at_k(recommended_list, bought_list, k=5):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)
    
    bought_list = bought_list  # Тут нет [:k] !!
    recommended_list = recommended_list[:k]
    
    flags = np.isin(recommended_list, bought_list)
    print(flags)
    
    
    precision = flags.sum() / len(recommended_list)
    
    
    return precision

precision_at_k(recommended, boughted, 8)

[False  True  True False  True  True False False]


0.5

In [30]:
def recall_at_k(recommended_list, bought_list, k=5):
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]
    
    flags = np.isin(recommended_list, bought_list)
    print(flags)
    
    recall = flags.sum() / len(bought_list)
    
    return recall
recall_at_k(recommended, boughted, 8)

[False  True  True False  True  True False False]


0.6666666666666666

In [22]:
boughted

[1, 3, 5, 7, 9, 11]

In [23]:
recommended

[2, 5, 7, 4, 11, 9, 8, 10, 12, 3]

In [25]:
np.isin(boughted, recommended[:8])

array([False, False,  True,  True,  True,  True])

In [31]:
rec_at_5 = (0+0+1+1+1+1)/6
rec_at_5

0.6666666666666666

In [70]:
def ap_k(recommended_list, bought_list, k=5):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]
    
    flags = np.isin(recommended_list, bought_list)
    
    if sum(flags) == 0:
        return 0
    
    sum_ = 0
    for i in range(1, k+1): 
        if flags[i-1] == True:
            p_k = precision_at_k(recommended_list, bought_list, k=i)
            sum_ += p_k
        print(sum_)
    result = sum_ / len(flags)
    
    return result
ap_k(recommended, boughted, 8)

0
[False  True]
0.5
[False  True  True]
1.1666666666666665
1.1666666666666665
[False  True  True False  True]
1.7666666666666666
[False  True  True False  True  True]
2.433333333333333
2.433333333333333
2.433333333333333


0.30416666666666664

In [71]:
for i in range(8):
    print(i+1, precision_at_k(recommended, boughted, i+1))

[False]
1 0.0
[False  True]
2 0.5
[False  True  True]
3 0.6666666666666666
[False  True  True False]
4 0.5
[False  True  True False  True]
5 0.6
[False  True  True False  True  True]
6 0.6666666666666666
[False  True  True False  True  True False]
7 0.5714285714285714
[False  True  True False  True  True False False]
8 0.5


In [72]:
np.isin(recommended, boughted).astype(int)

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1])

In [74]:
ap_at_8=(0*0+0.5*1+2/3*1+0.5*0+0.6*1+2/3*1)/8
ap_at_8

0.30416666666666664

In [56]:
from numpy import log

In [58]:
dcg_at_8 = (0/1+1/log(2)+1/log(3)+0/log(4)+1/log(5)+1/log(6)+0+0)/8
dcg_at_8

0.44154747857833254

In [60]:
idcg_at_8 = (1/1+1/log(2)+1/log(3)+1/log(4)+1/log(5)+1/log(6)+1/log(7)+1/log(8))/8
idcg_at_8

0.7810655048004851

In [63]:
ndcg_at_8 = dcg_at_8/idcg_at_8
ndcg_at_8

0.5653142737255068

In [64]:
from sklearn.metrics import ndcg_score

In [65]:
?ndcg_score

In [88]:
# ndcg_score(np.asarray([recommended]), np.asarray([boughted]), k=8)

In [90]:
np.log(2)

0.6931471805599453

In [93]:
def dcg_at_k(recommended_list, bought_list, k=5):
    
    bought_list = np.array(bought_list)
    recommended_list = np.array(recommended_list)[:k]
    
    flags = np.isin(recommended_list, bought_list)
    
    if sum(flags.astype(int)) == 0:
        return 0
    
    sum_ = 0
    for i in range(k): 
        if flags[i] == True:
            sum_ += 1/np.log(i+2)
        print(sum_)
    result = sum_ / len(flags)
    
    return result
dcg_at_k(recommended, boughted, 8)

0
0.9102392266268373
1.631586747071319
1.631586747071319
2.1896973736225664
2.703595715992317
2.703595715992317
2.703595715992317


0.3379494644990396

In [96]:
def ndcg_at_k(recommended_list, bought_list, k=5):
    
    ideal = dcg_at_k(bought_list, bought_list, k=len(bought_list))
    actual = dcg_at_k(recommended_list, bought_list, k=k)
    
    return actual / ideal
ndcg_at_k(recommended, boughted, 8)

1.4426950408889634
2.352934267515801
3.074281787960283
3.695616722519895
4.253727349071142
4.767625691440893
0
0.9102392266268373
1.631586747071319
1.631586747071319
2.1896973736225664
2.703595715992317
2.703595715992317
2.703595715992317


0.42530536544311187

In [97]:
# mrr...